homesite/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home, name="index")
]

homesite/budget/urls.py
from django.urls import path
from . import views


app_name = "budget"

urlpatterns = [
    path("", views.home, name="home"),

    path("operations", views.all_operation, name='operations'),
    path("operations/add", views.add_operation_from_dashboard, name="add_operation_dashboard"),
    path("operations/<int:operation_id>", views.edit_operation, name="edit_operation"),
    path("operations/<int:year>/<int:month>", views.all_operation_by_period, name="operations_by_period"),
    path("categories", views.all_categories, name="categories"),
    
    path("periods", views.all_periods, name="periods"),
    path("details/<int:category_id>/<int:year>/<int:month>", views.detail_category_by_period, name="detail_category_by_period"),
    path("details/<int:category_id>", views.detail_category, name="detail_category"),

    path("delete_category/<int:category_id>", views.delete_category, name="delete_category"),
    path("delete_operation/<int:operation_id>", views.delete_operation, name="delete_operation"),
    path("delete_account/<int:account_id>", views.delete_account, name="delete_account"),
    
    path("bank_accounts", views.all_bank_accounts, name="bank_accounts"),
]

homesite/homesite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("base.urls")),
    path("users/", include('users.urls')),
    path("budget/", include("budget.urls")),
    path('admin/', admin.site.urls),
]

homesite/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    path("register", views.register_user, name="register_user"), 
]

homesite/base/models.py
from django.db import models

# Create your models here.

homesite/base/views.py
import django.apps.registry as app_registry
from django.shortcuts import redirect, render


def home(request):
    if request.user.is_authenticated:
        APPS = app_registry.apps.get_app_configs()
        custom_install_apps = {}
        for app in APPS:
            try:
                if app.homesite_application: # type: ignore Custom Fields for application
                    if not app.homesite_tech_application: # type: ignore Custom Fields for application
                        custom_install_apps.update({app.name: app})
            except AttributeError:
                continue
        context = {"custom_applications": custom_install_apps}
        return render(request, "base/index.html", context)
    return redirect('users:login_user')

homesite/base/templates/base/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    {% block title %}{% endblock title %}
</head>
<body>
    {% block navbar %}
        {% include "base/navbar.html" %}
    {% endblock navbar %}
    
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {% else %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {% endif %}
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

            </br>
        {% block content %}
        <h1> Installed Applications </h1>
            <br>
            <div class="cards">
                {% for app_name,app_settings in custom_applications.items %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{app_name}}</h5>
                            <p> {{app_settings.application_home_url}}</p>
                            <a href="{{app_settings.application_home_url}}" class="btn btn-primary"> Go To Application</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endblock content %}
    </div>
     <!-- Option 1: Bootstrap Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

homesite/base/templates/base/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'base:index' %}">HomeSite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Applications
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'budget:home'%}">Budget</a></li>
                </ul>
              </li>
            </li>
          </ul>
          <ul class="navbar-nav me-2">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="#">{{user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:logout_user' %}">Log Out</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register_user' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login_user' %}">Log In</a>
            </li>
          </ul>
        {% endif%}
      </div>
    </div>
  </nav>