homesite/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home, name="index")
]

homesite/budget/urls.py
from django.urls import path
from . import views


app_name = "budget"

urlpatterns = [
    path("", views.home, name="home"),

    path("operations", views.all_operation, name='operations'),
    path("operations/add", views.add_operation_from_dashboard, name="add_operation_dashboard"),
    path("operations/<int:operation_id>", views.edit_operation, name="edit_operation"),
    path("operations/<int:year>/<int:month>", views.all_operation_by_period, name="operations_by_period"),
    path("categories", views.all_categories, name="categories"),
    
    path("periods", views.all_periods, name="periods"),
    path("details/<int:category_id>/<int:year>/<int:month>", views.detail_category_by_period, name="detail_category_by_period"),
    path("details/<int:category_id>", views.detail_category, name="detail_category"),

    path("delete_category/<int:category_id>", views.delete_category, name="delete_category"),
    path("delete_operation/<int:operation_id>", views.delete_operation, name="delete_operation"),
    path("delete_account/<int:account_id>", views.delete_account, name="delete_account"),
    
    path("bank_accounts", views.all_bank_accounts, name="bank_accounts"),
]

homesite/homesite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("base.urls")),
    path("users/", include('users.urls')),
    path("budget/", include("budget.urls")),
    path('admin/', admin.site.urls),
]

homesite/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    path("register", views.register_user, name="register_user"), 
]

homesite/budget/database/models.py
from datetime import date
from typing import Optional
from typing import List
from decimal import Decimal
from sqlalchemy import ForeignKey
from sqlalchemy import Date
from sqlalchemy import String
from sqlalchemy import Float
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship


class Base(DeclarativeBase):
    pass


class Users(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30), nullable=False)
    telegramID: Mapped[Optional[str]]
    owned_accounts: Mapped[List["Accounts"]] = relationship(back_populates="owner")
    user_operations: Mapped[List["Operations"]] = relationship(back_populates="user_id")

    def __repr__(self) -> str:
        return f"User({self.id=}, {self.name=}, {self.telegramID=})"


class Accounts(Base):
    __tablename__ = "accounts"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    bank: Mapped[str] = mapped_column(String(120), nullable=False)
    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"))
    owner: Mapped["Users"] = relationship(back_populates="owned_accounts")

    def __repr__(self) -> str:
        return f"Account({self.id=}, {self.name=}, {self.bank=}, {self.owner=})"


class Categories(Base):
    __tablename__ = "categories"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[int] = mapped_column(String(120), nullable=False)
    limit: Mapped[Decimal] = mapped_column(Float(3), nullable=True)

    def __repr__(self) -> str:
        return f"Category({self.name=}, {self.limit})"


class Operations(Base):
    __tablename__ = "operations"

    id: Mapped[int] = mapped_column(primary_key=True)
    operation_date: Mapped[date] = mapped_column(Date)
    account_id: Mapped[int] = mapped_column(ForeignKey("accounts.id"), nullable=False)
    category_id: Mapped[int] = mapped_column(
        ForeignKey("categories.id"), nullable=False
    )
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    user: Mapped["Users"] = relationship(back_populates="user_operations")
    amount: Mapped[Decimal] = mapped_column(Float(3), nullable=False)

homesite/budget/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import User


class BankAccount(models.Model):
    """Реализует функционал учета по банковским картам"""
    name = models.CharField(max_length=20, unique=True)
    bank = models.CharField(max_length=20, unique=False)
    owned_by = models.ForeignKey(User, on_delete=models.PROTECT)
    
    def __str__(self) -> str:
        return f"{self.bank}: {self.name}"

class Period(models.Model):
    """Periods Class"""
    name = models.CharField(max_length=20, unique=True)
    start_date = models.DateField(auto_now=False, auto_now_add=False)
    end_date = models.DateField(auto_now=False, auto_now_add=False)
    year = models.IntegerField()
    month = models.IntegerField()
    short_name = models.CharField(max_length=20)

    def __str__(self) -> str:
        return f"{self.name}"


class Category(models.Model):
    """Category Class"""

    name = models.CharField(max_length=20, unique=True)
    limit = models.DecimalField(decimal_places=2, max_digits=8, null=True)

    def __str__(self) -> str:
        return f"{self.name}"


class DetalisationDimension(models.Model):
    """ User dimensions class """
    name = models.CharField(max_length=30)


class DetalisationDimensionItem(models.Model):
    """ User dimensions items"""
    name = models.CharField(max_length=30)
    parent_id = models.IntegerField(default=-1)
    dim_id = models.ForeignKey(DetalisationDimension, on_delete=models.PROTECT)

class Operation(models.Model):
    """Operation class"""

    DEBIT = "Dr"
    CREDIT = "Cr"

    OPER_TYPE_CHOICES = {
        DEBIT: "Доход",
        CREDIT: "Расход"
    }

    operation_date = models.DateField(auto_now=False, auto_now_add=False)
    operation_period = models.ForeignKey(Period, on_delete=models.PROTECT, null=True)
    bank_account = models.ForeignKey(BankAccount, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    operation_type = models.CharField(max_length=2, choices=OPER_TYPE_CHOICES, default=CREDIT)
    detalisation = models.JSONField(null=True, blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    comment = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.operation_date}: {self.comment}"

homesite/budget/forms.py
from typing import Any
from django import forms
from .models import Operation, Category, BankAccount
from budget.logic.queries import get_all_category, get_all_bank_accounts


class BankAccountForm(forms.ModelForm):
    
    name = forms.CharField(label="Имя счета")
    bank = forms.CharField(label="Банк")
    
    class Meta:
        model = BankAccount
        fields = ("name", "bank")
    
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs["class"] = "form-control form-control-sm"
        self.fields["bank"].widget.attrs["class"] = "form-control form-control-sm"
        self.fields["name"].widget.attrs["placeholder"] = "Имя счета"
        self.fields["bank"].widget.attrs["placeholder"] = "Имя банка"


class OperationForm(forms.ModelForm):
    operation_date = forms.DateField()
    category = forms.ModelChoiceField(queryset=get_all_category())
    bank_account = forms.ModelChoiceField(queryset=get_all_bank_accounts())
    amount = forms.DecimalField()
    operation_type = forms.ChoiceField(label="Тип категории", choices=Operation.OPER_TYPE_CHOICES)
    comment = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Operation
        fields = ("operation_date", "category", "bank_account", "operation_type", "amount", "comment")

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["operation_date"].widget = forms.widgets.DateInput(
            format = ('%Y-%m-%d'),
            attrs={
                "type": "date",
                "placeholder": "yyyy-mm-dd (DOB)",
                "class": "form-control",
                "autocomplete": "off"
            }
        )
        self.fields["category"].widget.attrs["class"] = "form-control"
        self.fields["amount"].widget.attrs["class"] = "form-control"
        self.fields["bank_account"].widget.attrs["class"] = "form-control form-select"
        self.fields["operation_type"].widget.attrs["class"] = "form-select form-select"
        self.fields["comment"].widget.attrs["class"] = "form-control"

class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        label="Имя категории",
        max_length=20,
        required=True
    )
    limit = forms.DecimalField(decimal_places=2, max_digits=8, required=False)

    class Meta:
        model = Category
        fields = ("name", "limit")

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs["class"] = "form-control form-control-sm"
        self.fields["name"].widget.attrs["placeholder"] = "Имя категории"
        self.fields["limit"].widget.attrs["class"] = "form-control form-control-sm"
        self.fields["limit"].widget.attrs["placeholder"] = "Лимит за период"
        

homesite/budget/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.db.models import Sum


import budget.logic as app_logic
import budget.logic.queries as queries

from .models import Category, Operation, Period, BankAccount
from .forms import CategoryForm, OperationForm, BankAccountForm



def home(request):

    """Построение начального Dashboard по текущему состоянию бюджета."""
    context = app_logic.homepage_data()
    return render(request, "budget/dashboard.html", context)

# Periods

def all_periods(request):
    context = {}
    return render(request, "budget/periods_settings.html", context)

def specify_period(request, period_id):
    return render(request, "budget/dashboard.html", context)

# Category

def all_categories(request):
    if request.method == "POST":
        errors = app_logic.create_category(CategoryForm(request.POST))
        if errors:
            for err in errors:
                messages.error(request, f"{err}")
        else:
            messages.success(request, "Добавлена новая категория")
        return redirect("budget:categories")
    categories = queries.get_all_category()
    form = CategoryForm()
    context = {"categories": categories, "form": form}
    return render(request, "budget/categories.html", context)

def delete_category(request, category_id):
    app_logic.delete_category(category_id)
    return redirect("budget:categories")

def detail_category_by_period(request, category_id, year, month):
    category = get_object_or_404(Category, pk=category_id)
    period = queries.get_period_by_year_month(year, month)
    operations = queries.get_operations_by_period(period).filter(category=category_id).order_by("operation_date")
    return render(
        request,
        "budget/category_detail.html",
        {"category": category, "operations": operations, "period": period},
    )

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    operations = (
        Operation.objects.all().filter(category=category_id).order_by("operation_date")
    )
    return render(
        request,
        "budget/category_detail.html",
        {"category": category, "operations": operations, "period": "Все периоды"},
    )

# Operations

def edit_operation(request, operation_id):
    # ! TODO: MAKE REDIRECT WORK !!!
    edit_operation = get_object_or_404(Operation, pk=operation_id)
    form = OperationForm(request.POST or None, instance=edit_operation)
    if form.is_valid():
        app_logic.save_operation(form)
        return redirect("budget:operations")
    return render(request, "budget/edit_operation.html", 
                  context={"form":form, "edit_operation": edit_operation})
        

def delete_operation(request, operation_id):
    operation_to_delete = get_object_or_404(Operation, pk=operation_id)
    operation_to_delete.delete()
    return redirect(request.META.get("HTTP_REFERER"))

def all_operation_by_period(request, year, month):
    period = queries.get_period_by_year_month(year, month)
    operations = queries.get_operations_by_period(period).order_by("operation_date", "category")
    sum_all_operations = queries.get_operations_by_period(period).aggregate(all_sum=Sum("amount"))
    if request.method == "POST":
        form = OperationForm(request.POST)
        if form.is_valid():
            app_logic.save_operation(form)
            messages.success(request, "Added new Operation")
            sum_all_operations = Operation.objects.aggregate(all_sum=Sum("amount"))
            return redirect("budget:operations")
    else:
        form = OperationForm()
        return render(
            request,
            "budget/operations.html",
            {
                "form": form,
                "operations": operations,
                "all_sum": sum_all_operations["all_sum"],
            },
        )
    return render(
        request,
        "budget/operations.html",
        {
            "form": form,
            "operations": operations,
            "all_sum": sum_all_operations["all_sum"],
        },
    )

def all_operation(request):
    today = datetime.now()
    return all_operation_by_period(request, today.year, today.month)

def add_operation_from_dashboard(request):
    if request.method == "POST":
        form = OperationForm(request.POST)
        if form.is_valid():
            app_logic.save_operation(form)
            messages.success(request, "Added new Operation")
            return redirect("budget:home")
    else:
        form = OperationForm()
        return render(request, "budget/edit_operation.html", {"form": form})

# Bank

def all_bank_accounts(request):
    accounts = queries.get_all_bank_accounts()
    if request.method == "POST":
        form = BankAccountForm(request.POST)
        if form.is_valid():
            app_logic.save_bank_account(form, request.user)
            messages.success(request, "Added new Bank Account")
            return redirect("budget:bank_accounts")
    else:
        form = BankAccountForm()
        return render(request, "budget/bank_account.html", {"form": form, "accounts": accounts})

def delete_account(request, account_id):
    get_object_or_404(BankAccount, pk=account_id).delete()
    return redirect(request.META.get("HTTP_REFERER"))

homesite/budget/templates/budget/all_operation.html
{% extends 'base/index.html' %}
{% block title %}
    <title> Budget - Add Operation </title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}


{% block content %}
</br>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addOperationModal">
      Add new operation
    </button>

    <!-- Modal -->
    <div class="modal fade" id="addOperationModal" tabindex="-1" aria-labelledby="addOperationModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addOperationModalLabel">Добавление операции</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <div class="modal-body">
              <div class="col-md-6 offset-md-3">
                <form method="post" action="">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          Your Form Has Errors
                          {% for field in form %}
                              {% if field.errors %}
                                  {{ field.errors }}
                              {% endif %}
                          {% endfor %}
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    {{ form.as_p }}
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
              </div>
          </div>

        </div>
      </div>
    </div>

    </br>

    <h1> All Operations </h1>

    <table class="table table-bordered table-hover table-sm">
        <thead>
          <tr>
            <th scope="col">Период</th>
            <th scope="col">Категория</th>
            <th scope="col">Сумма</th>
            <th class="border-0" scope="col">Комментарий</th>
          </tr>
        </thead>
        <tbody>
        {% for operation in operations %}
          <tr>
            <td scope="row">{{operation.operation_date|date:'F Y'}}</td>
            <td>{{operation.category}}</td>
            <td>{{operation.amount|floatformat:"2g"}} &#8381;</td>
            <td class="border-0">{{operation.comment}}</td>
            <td class="border-0"><a href={% url "budget:delete_operation" operation.id %}><i class="bi bi-trash"></i></a>
          </tr>
        {% endfor %}
        </tbody>
        <tfoot>
          <th class="text-end"> Итого: </th>
          <td class="border-0">  </td>
          <td class="border-0"> {{all_sum|floatformat:"2g"}} &#8381; </td>
          <td class="border-0"> </td>
        </tfoot>
      </table>


{% endblock content %}

homesite/budget/templates/budget/categories.html
{% extends "base/index.html" %}

{% block title %}
    <title> Budget - Categories</title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}

{% block content %}
    
    <h1> Добавление категории</h1>
    </br>
    <form method="post" action="">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Ошибки на форме
            {% for field in form %}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        <div class="row">
            {% for field in form %}
                <div class="col-3"> 
                    {{ field }}
                </div>
            {% endfor %}
        </div>
        </br>
        <button type="submit" class="btn btn btn-outline-success btn-sm">Добавить категорию</button>
    </form>
    </br>
    <h1> Список категорий </h1>

    <table class="table table-bordered table-hover table-sm">
        <thead>
            <tr>
                <th scope="col"> Имя категории </th>
                <th scope="col"> Лимит за период </th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td scope="row"><a href= "{% url 'budget:detail_category' category.id %}"> {{category.name}}</td>
                    <td> {% if category.limit is None %}
                            <i class="bi bi-infinity"></i>
                        {% else %} 
                            {{ category.limit }}
                        {% endif %} 
                        </td>
                    <td class="border-0"><a href={% url "budget:delete_category" category.id %}><i class="bi bi-trash"></i></a>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    </br>

   

{% endblock content %}

homesite/budget/templates/budget/category_detail.html
{% extends 'base/index.html' %}
{% block title %}
    <title> Budget - Detail category </title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}

{% block content %}
    <h1> {{category.name}} за {{period}} </h1>
    <table class="table table-bordered table-hover table-sm">
        <tr>
            <th> Дата Операции </th>
            <th> Тип Операции </th>
            <th> Сумма </th>
            <th> Комментарий </th>
        </tr>
    {% for operation in operations %}
        <tr>
            <td>{{ operation.operation_date|date:'d F Y'}} </td>
            <td>{{ operation.get_operation_type_display}}</td>
            <td>{{ operation.amount}} </td>
            <td>{{ operation.comment}} </td>
            <td class="border-0"><a href={% url "budget:edit_operation" operation.id %}><i class="bi bi-pencil"></i></a>
            <td class="border-0"><a href={% url "budget:delete_operation" operation.id %}><i class="bi bi-trash"></i></a>
        </tr> 
    {% endfor %}
    </table>
{% endblock content %}

homesite/budget/templates/budget/dashboard.html
{% extends "base/index.html" %}

{% block title %}
    <title> Budget</title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}

{% block content %}
    <div class="row">  
        <div class="col-9"><h1> Dashboard</h1></div> 
    </div>
    <div class="row">
        <div class="card m-2" style="width: 18rem; height: 9rem;">
            <div class="card-body">
                <h4 class="card-title"> Заработано:</h4>
                <p class="card-text"><font class="text-success">{{get_all_category.get_by_category__sum| floatformat:"2g"}} &#8381;</font></p>
                <a href="#" class="btn btn-primary">Детали</a>
            </div>
        </div>
        <div class="card m-2" style="width: 18rem; height: 9rem; padding-left: 2px">
            <div class="card-body">
                <h4 class="card-title"> Потрачено:</h4>
                <p class="card-text"><font class="text-danger">{{spend_all_category.spend_by_category__sum| floatformat:"2g"}} &#8381;</font></p>
                <a href="#" class="btn btn-primary">Детали</a>
            </div>
        </div>
        <div class="card m-2" style="width: 18rem; height: 9rem; padding-left: 2px">
            <div class="card-body">
                <h4 class="card-title"> Остаток средств:</h4>
                <p class="card-text"><font class="text-block">{{rest_of_money| floatformat:"2g"}} &#8381;</font></p>
                <a href="#" class="btn btn-primary">Детали</a>
            </div>
        </div>

    </div>
    </br>
    <div class="row">
        <div class="col-7 m-2">
            <div class="row  mb-1">
                <div class="col-11"> 
                    <h4> Траты</h4>
                </div>
                <div class="col-1">
                    <form action= "{% url 'budget:add_operation_dashboard' %}">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-plus-circle"></i></button>
                    </form>
                </div>
            </div>
            <div class="row">
                <table class="table table-bordered table-hover table-sm">
                    <tr>
                        <th> Категория </th>
                        <th> Лимит на период</th>
                        <th> Остаток </th>
                        <th> Потрачено </th>
                    </tr>
                {% for operation in operations_credit %}
                <tr>
                    <td> <a href= "{% url 'budget:detail_category_by_period' operation.category__id period_today.year period_today.month %}">{{ operation.category__name}} </td>
                    <td>{{ operation.category__limit|floatformat:"2g"}} &#8381;</td>
                    <td>{{ operation.rest_by_category|floatformat:"2g"}} &#8381;</td>
                    <td>{{ operation.spend_by_category|floatformat:"2g"}} &#8381;</td>
                </tr> 
                {% endfor %}
                </table>
            </div>
        </div>
        <div class="col-5">
            <div class="row mb-1">
                <div class="col-11"> 
                    <h4> Поступления</h4>
                </div>
                <div class="col-1">
                    <form action= "{% url 'budget:add_operation_dashboard' %}">
                    <button type="submit" class="btn btn-primary"><i class="bi bi-plus-circle"></i></button>
                    </form>
                </div>
            </div>
            <div class="rowo">
                <table class="table table-bordered table-hover table-sm table-responsive">
                    <tr>
                        <th> Категория </th>
                        <th> Получено за период</th>

                    </tr>
                {% for operation in operations_debit %}
                <tr>
                    <td> <a href= "{% url 'budget:detail_category_by_period' operation.category__id period_today.year period_today.month %}">{{ operation.category__name}} </td>
                    <td>{{ operation.get_by_category|floatformat:"2g"}} &#8381;</td>
                </tr> 
                {% endfor %}
                </table>
            </div>

{% endblock content %}

homesite/budget/templates/budget/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'base:index' %}">HomeSite</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Budget
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'budget:home'%}">Дашборд</a></li>
                  <li><a class="dropdown-item" href="{% url 'budget:categories'%}">Категории</a></li>
                  <li><a class="dropdown-item" href="{% url 'budget:operations'%}">Операции</a></li>
                  <li><a class="dropdown-item" href="{% url 'budget:bank_accounts'%}">Банковские счета</a></li>
                </ul>
              </li>
            </li>
          </ul>
          <ul class="navbar-nav me-2">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="#">{{user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'users:logout_user' %}">Log Out</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register_user' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login_user' %}">Log In</a>
            </li>
          </ul>
        {% endif%}
      </div>
    </div>
  </nav>

homesite/budget/templates/budget/operations.html
{% extends 'base/index.html' %}

{% block title %}
    <title> Budget - Add Operation </title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}


{% block content %}
</br>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addOperationModal">
      Add new operation
    </button>

    <!-- Modal -->
    <div class="modal fade" id="addOperationModal" tabindex="-1" aria-labelledby="addOperationModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addOperationModalLabel">Добавление операции</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <div class="modal-body">
              <div class="col-md-6 offset-md-3">
                <form method="post" action="">
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          Your Form Has Errors
                          {% for field in form %}
                              {% if field.errors %}
                                  {{ field.errors }}
                              {% endif %}
                          {% endfor %}
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    {{ form.as_p }}
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
              </div>
          </div>

        </div>
      </div>
    </div>

    </br>

    <h1> All Operations </h1>

    <table class="table table-bordered table-hover table-sm">
        <thead>
          <tr>
            <th scope="col">Дата операции</th>
            <th scope="col">Период отчета</th>
            <th scope="col">Банковский счет</th>
            <th scope="col">Категория</th>
            <th scope="col">Тип операции</th>
            <th scope="col">Сумма</th>
            <th class="border-0" scope="col">Комментарий</th>
          </tr>
        </thead>
        <tbody>
        {% for operation in operations %}
          <tr>
            <td scope="row">{{operation.operation_date|date:'d M Y'}}</td>
            <td>{{operation.operation_period}}</td>
            <td>{{operation.bank_account}}</td>
            <td>{{operation.category}}</td>
            <td>{{operation.get_operation_type_display}}</td>
            <td>{{operation.amount|floatformat:"2g"}} &#8381;</td>
            <td class="border-0">{{operation.comment}}</td>
            <td class="border-0"><a href={% url "budget:edit_operation" operation.id %}><i class="bi bi-pencil"></i></a>
            <td class="border-0"><a href={% url "budget:delete_operation" operation.id %}><i class="bi bi-trash"></i></a>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock content %}

homesite/budget/templates/budget/periods_settings.html
{% extends 'base/index.html' %}

{% block title %}
    <title> Budget - Periods </title>
{% endblock title %}

{% block navbar %}
    {% include "budget/navbar.html" %}
{% endblock navbar%}



{% block content %}



{% endblock content %}